### ISSUE TITLE
Cms fields tab name Facebook is too general

### ISSUE THREAD

**Issue by axyr** [heyday/silverstripe-facebookimage#2]
Its opiniated, but I use Facebook, Twitter, LinkedIn, Instagram as fieldnames for the links in SiteConfig.
But when using this module I should pick another name for these pretty common fields..

I therefore think that the tab name Facebook is too general or should at least be configurable..

I'm happy too make pull request...

**Comment by glenn-bautista** [comment]
## I’m open to your suggestion. I think we could just change tab name. What name would you suggest?

Glenn Bautista Senior Developer
Ph. 04 831 5130   heyday.co.nzhttp://heyday.co.nz/

From: Martijn van Nieuwenhoven
Reply-To: heyday/silverstripe-facebookimage
Date: Tuesday, 15 March 2016 2:06 am
To: heyday/silverstripe-facebookimage
Subject: [silverstripe-facebookimage] Cms fields tab name Facebook is too general (#2)

Its opiniated, but I use Facebook, Twitter, LinkedIn, Instagram as fieldnames for the links in SiteConfig.
But when using this module I should pick another name for these pretty common fields..

I therefore think that the tab name Facebook is too general or should at least be configurable..

I'm happy too make pull request...
